package io.github.aililuola.mathproofmesh.concurrency;

public enum ResearchConcurrencyFailurePoint {
  NONE,
  AFTER_EPOCH_PLANNED,
  AFTER_TASKS_RECORDED,
  AFTER_AGENT_LEASE_ACQUIRED,
  AFTER_PROVIDER_RESPONSE_DURABLE,
  AFTER_TASK_RESULT_DURABLE,
  AFTER_ALL_SETTLED,
  AFTER_MERGE_PLAN_DURABLE,
  AFTER_AUTHORITY_MUTATION,
  AFTER_EPOCH_COMMIT,
  AFTER_CHECKPOINT_ATOMIC_MOVE
}
