package io.github.aililuola.mathproofmesh.concurrency;

public enum ResearchWorkKind {
  ROUTE_EXPLORATION,
  ROUTE_REVIEW,
  CLAIM_STATEMENT_FALSIFICATION,
  CLAIM_PROOF_AUDIT,
  CLAIM_MINIMAL_REPAIR,
  CLAIM_BLIND_ADJUDICATION,
  FOCUSED_PROVER,
  FOCUSED_FALSIFIER,
  FOCUSED_REPROVER,
  DEPENDENCY_AUDITOR,
  PIVOT_PROPOSAL,
  PIVOT_REVIEW,
  COMPUTATION,
  SYNTHESIS_REVIEW,
  FINAL_REVIEW
}
