package io.github.aililuola.mathproofmesh.strategydiversity;

public enum StrategyCandidateStatus {
  CAPTURED,
  BLUEPRINT_COMPILED,
  BASE_VALIDATED,
  PREFLIGHTED,
  REJECTED_INVALID,
  REJECTED_NEGATIVE,
  REJECTED_REFUTED_REQUIRED_CLAIM,
  QUARANTINED_PREFLIGHT_ERROR,
  QUARANTINED_COMMON_MODE,
  SHADOW_DUPLICATE,
  SELECTED,
  NOT_SELECTED,
  REPLENISHMENT_CANDIDATE,
  LEGACY_ACTIVE
}
