package io.github.aililuola.mathproofmesh.strategydiversity;

public enum StrategyMechanismPrimitive {
  DIRECT,
  CONTRADICTION,
  INDUCTION,
  MINIMAL_COUNTEREXAMPLE,
  EXTREMAL,
  INVARIANT,
  CONSTRUCTIVE,
  DECOMPOSITION,
  TRANSFORMATION,
  DUALITY,
  ALGEBRAIC,
  GEOMETRIC,
  SPECTRAL,
  PROBABILISTIC,
  COMBINATORIAL,
  FINITE_STATE,
  COMPUTATIONAL_FALSIFICATION,
  UNKNOWN
}
