package io.github.aililuola.mathproofmesh.communication.artifact;

public enum BrokerArtifactSourceKind {
  CLAIM_COURT_VERIFIED,
  VERIFIED_COUNTEREXAMPLE,
  REFUTED_STATEMENT,
  REVIEWED_PROOF_OBSTRUCTION,
  VERIFIED_CONSTRUCTION,
  AUDITED_EXACT_EXAMPLE,
  TRUSTED_FORMAL_CERTIFICATE,
  BOUNDED_EVIDENCE,
  RAW_RESEARCH_FINDING,
  MODEL_DECLARATION
}
