package io.github.aililuola.mathproofmesh.contract;

public enum BrokerVerifiedEffectType {
  COMMITTED_STEP_REUSE,
  VERIFIED_CLAIM_DERIVED,
  EXACT_CLAIM_REFUTED,
  OBLIGATION_CLOSED,
  DEPENDENCY_RETIRED,
  FOCUS_CHANGED,
  LOCAL_REPAIR_BOUND,
  SEMANTIC_PIVOT_BOUND,
  COMPUTATION_PLAN_BOUND,
  FINAL_PROOF_CITATION
}
