package io.github.aililuola.mathproofmesh.contract;

public enum BrokerArtifactUseKind {
  PREMISE_IN_PROOF_STEP,
  SUPPORTS_CLAIM,
  REFUTES_CLAIM,
  RETIRES_DEPENDENCY,
  SELECTS_FOCUS_OBLIGATION,
  TRIGGERS_LOCAL_REPAIR,
  TRIGGERS_SEMANTIC_PIVOT,
  SUPPORTS_COMPUTATION_PLAN,
  CITED_IN_FINAL_PROOF
}
