package io.github.aililuola.mathproofmesh.contract;

public enum ProofIssueKind {
  INVALID_INFERENCE,
  MISSING_JUSTIFICATION,
  MISSING_DEPENDENCY,
  CIRCULAR_REASONING,
  QUANTIFIER_SCOPE_ERROR,
  CASE_COVERAGE_GAP,
  CALCULATION_ERROR,
  CONSTRUCTION_NOT_WELL_DEFINED,
  EVIDENCE_MISMATCH,
  CITATION_OR_TOOL_EVIDENCE_GAP,
  STATEMENT_REFORMULATION_REQUIRED,
  GLOBAL_PROOF_ARCHITECTURE_FAILURE,
  UNKNOWN
}
