package io.github.aililuola.mathproofmesh.runstate;

public enum RunStateTransitionTrigger {
  RUN_CREATED,
  EXECUTION_STARTED,
  SEMANTIC_CHECKPOINT_COMMITTED,
  USAGE_RECONCILED,
  EXECUTION_SUCCEEDED,
  EXECUTION_FAILED,
  EXECUTION_INTERRUPTED,
  EXECUTION_CANCELLED,
  FINAL_VERIFICATION_PASSED,
  FINAL_VERIFICATION_FAILED,
  CAMPAIGN_MARKED_RECOVERABLE,
  REPORT_PROJECTED,
  REPORT_PROJECTION_FAILED,
  RESUME_STARTED,
  LEGACY_STATE_MIGRATED,
  RECONCILIATION_REPAIRED
}
