package io.github.aililuola.mathproofmesh.runstate;

public enum RunStateFailurePoint {
  AFTER_SEMANTIC_CHECKPOINT,
  AFTER_USAGE_RECONCILIATION,
  AFTER_AUTHORITY_STATE_COMMIT,
  AFTER_RUN_RESULT_PROJECTION,
  AFTER_DESKTOP_METADATA_PROJECTION,
  AFTER_REPORT_PROJECTION,
  AFTER_API_VIEW_PROJECTION,
  AFTER_ATOMIC_STATE_MOVE
}
