"""Goal-plan-failure-utility proof control sidecar."""

from .action_dispatcher import ControlActionDispatcher
from .controller import ProofControlLayer
from .models import (
    AbstractStructureProposal,
    AbstractRealizerExtraction,
    BlueprintRewriteRequest,
    BottleneckCluster,
    ClaimGoalLink,
    ControlActionRecord,
    ControlActionResult,
    ControlActionStatus,
    ControlActionType,
    ContinueGateRecord,
    CriticalAssumption,
    FailureClassificationRecord,
    GateVerdict,
    GoalRelation,
    IndexScope,
    InductionBlueprintNode,
    InductionMeasureProposal,
    InferenceRiskRecord,
    InferenceRiskType,
    MessageUtilityContract,
    MessageUsageReceipt,
    MinimalBridgeProposal,
    NearMissRecord,
    ObjectScope,
    ProofFailureClass,
    ProofRole,
    RealizerCandidate,
    RealizerFailureType,
    RealizerRepairResult,
    RealizerRepairTask,
    RouteAdmissionRecord,
    ScopeRelation,
    ScopeSignature,
    SynthesisReadinessRecord,
    UniformityScope,
)
from .state import ProofControlState
from .falsification import (
    FastLaneEligibility,
    FalsificationDisposition,
    classify_falsification_result,
    evaluate_fast_lane_eligibility,
)
from .gates import (
    ContinueDeepeningGate,
    RouteAdmissionGate,
    SynthesisReadinessGate,
)

__all__ = [
    "AbstractStructureProposal",
    "AbstractRealizerExtraction",
    "BlueprintRewriteRequest",
    "BottleneckCluster",
    "ClaimGoalLink",
    "ControlActionDispatcher",
    "ControlActionRecord",
    "ControlActionResult",
    "ControlActionStatus",
    "ControlActionType",
    "ContinueGateRecord",
    "CriticalAssumption",
    "FailureClassificationRecord",
    "FastLaneEligibility",
    "FalsificationDisposition",
    "GateVerdict",
    "GoalRelation",
    "IndexScope",
    "InductionBlueprintNode",
    "InductionMeasureProposal",
    "InferenceRiskRecord",
    "InferenceRiskType",
    "MessageUtilityContract",
    "MessageUsageReceipt",
    "MinimalBridgeProposal",
    "NearMissRecord",
    "ObjectScope",
    "ProofControlState",
    "ProofControlLayer",
    "ProofFailureClass",
    "ProofRole",
    "RealizerCandidate",
    "RealizerFailureType",
    "RealizerRepairResult",
    "RealizerRepairTask",
    "RouteAdmissionRecord",
    "RouteAdmissionGate",
    "ScopeRelation",
    "ScopeSignature",
    "SynthesisReadinessRecord",
    "SynthesisReadinessGate",
    "ContinueDeepeningGate",
    "UniformityScope",
    "classify_falsification_result",
    "evaluate_fast_lane_eligibility",
]
