package io.github.aililuola.mathproofmesh.desktop;

enum ClaimCourtFailurePoint {
  NONE,
  AFTER_CLAIM_FREEZE,
  AFTER_STATEMENT_RESULT_DURABLE,
  AFTER_PROOF_AUDIT_RESULT,
  AFTER_REPAIR_PATCH_VALIDATION,
  AFTER_REPAIRED_REVISION_WRITE,
  AFTER_BLIND_RESULT_DURABLE,
  AFTER_FINAL_OUTCOME_BEFORE_PROJECTION,
  AFTER_LEMMA_MEMORY_PROJECTION,
  AFTER_FACT_PROJECTION_BEFORE_PERSIST,
  AFTER_FINAL_CHECKPOINT_PERSIST
}
