package io.github.aililuola.mathproofmesh.computation;

public enum ComputationExecutionFailurePoint {
  AFTER_CAPABILITY_RESOLVE,
  AFTER_EXECUTION_ADMITTED,
  AFTER_PRODUCER_BEFORE_RESULT_DURABLE,
  AFTER_RESULT_DURABLE,
  AFTER_VERIFICATION_DURABLE,
  AFTER_AUTHORITY_APPLIED_BEFORE_CHECKPOINT,
  AFTER_ATOMIC_CHECKPOINT_MOVE
}
