package io.github.aililuola.mathproofmesh.computation;

public enum ComputationExecutionFailurePoint {
  AFTER_CAPABILITY_RESOLVE,
  AFTER_EXECUTION_ADMITTED,
  AFTER_PRODUCER_BEFORE_RESULT_DURABLE,
  AFTER_RESULT_DURABLE,
  AFTER_VERIFICATION_DURABLE,
  AFTER_PROJECTION_READY,
  AFTER_COUNTEREXAMPLE_MUTATION_BEFORE_LEDGER_COMMIT,
  AFTER_FACT_MUTATION_BEFORE_LEDGER_COMMIT,
  AFTER_LEDGER_COMMIT_BEFORE_CHECKPOINT,
  AFTER_AUTHORITY_APPLIED_BEFORE_CHECKPOINT,
  AFTER_ATOMIC_CHECKPOINT_MOVE
}
